name: Deploy Chatbot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      AWS_REGION: us-east-1
      ECR_REPO: 727646479568.dkr.ecr.us-east-1.amazonaws.com/chatbot

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 727646479568.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t chatbot .

      - name: Tag image
        run: docker tag chatbot:latest 727646479568.dkr.ecr.us-east-1.amazonaws.com/chatbot:latest

      - name: Push image to ECR
        run: docker push 727646479568.dkr.ecr.us-east-1.amazonaws.com/chatbot:latest

      - name: Stop old container
        run: |
          docker stop chatbot || true
          docker rm chatbot || true

      - name: Run new container
        run: |
          docker run -d \
            --name chatbot \
            --restart always \
            -p 8000:8000 \
            -p 8501:8501 \
            727646479568.dkr.ecr.us-east-1.amazonaws.com/chatbot:latest

      - name: Verify
        run: docker ps -a

      - name: Logs
        if: always()
        run: docker logs chatbot || true